### ISSUE TITLE
Styled Media Receiver?

### ISSUE THREAD

**Issue by wa4557** [balloob/pychromecast#106]
I have tried to find out in the source code, but I was not able to see if it is possible to connect somehow to a [Styled Media Receiver](https://developers.google.com/cast/docs/styled_receiver). 
A styled media receiver does not have its own namespace (as far as I understand) and therefore the example provided in the README doesn't work unfortunately. 

There is a `supporting_app_id`, but as far as I understand it is only called if the current namespace is unsupported.

**Comment by keredson** [comment]
so what's the suggested way of calling the styled media receiver? 

calling `cast.media_controller.app_id = MY_APP_ID` before anything else seems to work, but is this correct?

**Comment by rafikee** [comment]
Have you figured out how to do this btw? I tried as you mentioned unsuccessfully.

**Comment by emontnemery** [comment]
What @keredson mentions will use an alternative app for the media controller instead of the default media receiver.
Please open a new issue where you explain exactly what you did, what happened, and what you expected.
