### ISSUE TITLE
How to handle lost connections?

### ISSUE THREAD

**Issue by KalleSven** [balloob/pychromecast#107]
I'm trying to put together a script that will run in the background, sending photos to the chromecast whenever idle. However, I am having some troubles handling lost connections (Chromecast is powered off). The example below would cause the script to freeze when trying to play media. Is there any way to query the chromecast to make sure we still have a working connection? Using cast.status och mc.status seems to give me cached values to no use.

Thanks!

```
cast = pychromecast.get_chromecast(friendly_name="MyCC")
cast.wait()
time.sleep(30)
# Chromecast is powered off for some reson during time.sleep
mc = cast.media_controller
mc.play_media('http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4', 'video/mp4')
```

**Comment by soreau** [comment]
@KalleSven I managed to do it in [catt-qt](github.com/soreau/catt-qt) with [this patch](https://github.com/balloob/pychromecast/commit/15655117236b4d856677d5c58a0a29883665003a).

**Comment by balloob** [comment]
Patch is merged now.
