### ISSUE TITLE
Chromecast Audio status when playing as member of a group

### ISSUE THREAD

**Issue by emontnemery** [balloob/pychromecast#111]
When a Chromecast Audio is playing media as a member of a group, the returned MEDIA_STATUS is empty:
`{u'status': [], u'type': u'MEDIA_STATUS', u'requestId': 3}`

What would be the correct way reliably know if a particular device is playing, including when it's acting as a member of a group?
It would be possible to loop over all groups of which the device is a member, but:
- How to get a list of groups of which the device is a member?
- What if several groups, of which a particular device is a member, are playing at the same time?

Edit:
Partial solution:
In each group, one Chromecast will be elected 'leader', while the remaining players in the same group will be 'followers'.

When the **leader** is playing or paused, it will report an app_id of 'MultizoneLeader' and a 'session_id' which is same as the 'session_id' of the group it is leading. Hence, state of the leader can be deduced from the `media_controller.status.player_state` state of the matching group.

The **followers** will report an app_id of 'MultizoneFollower'.
Doing:
`requests.get('http://' + follower_ip + ':8008/setup/eureka_info?params=multizone')`
will return, among other group related settings, a list of groups in which the follower is a member.
The state of the follower can be guessed by comparing status.status_text and status.display_name between the follower and groups in which it is a member.

There is probably a more straight forward way to do this.

**Comment by emontnemery** [comment]
I've been using the proposed solution in the issue description since writing the issue, and it works well.

@balloob Maybe this should be added to pychromecast to, for example, fix home-assistant/home-assistant#8531

Would the following be an OK implementation
 - A group type cast will have a list of members, with callbacks when the list is changed
 - A "normal" cast will have a list of group memberships, with callbacks when the list is changed

(Unfortunately, I've not found a better way than polling http requests)

**Comment by emontnemery** [comment]
Update:

We do get these kind of updates when a group member:
- Is added to group, for example after booting:
`[192.168.0.177:42412] Got data: "{'device': {'capabilities': 4, 'deviceId': '42feced1-d942-3823-2fba-92623e2682f3', 'name': 'Living room', 'volume': {'level': 0.22923965752124786, 'muted': False}}, 'requestId': 0, 'type': 'DEVICE_ADDED'}"`
- Is removed from group, for example when it is power cycled:
`[192.168.0.177:42412] Got data: "{'deviceId': '42feced1-d942-3823-2fba-92623e2682f3', 'requestId': 0, 'type': 'DEVICE_REMOVED'}"`
- Group member's volume was changed:
`[192.168.0.177:42412] Got data: "{'device': {'capabilities': 4, 'deviceId': '42feced1-d942-3823-2fba-92623e2682f3', 'name': 'Living room', 'volume': {'level': 0.28999999165534973, 'muted': False}}, 'requestId': 0, 'type': 'DEVICE_UPDATED'}"`

The messages are supported by this lib, but doesn't seem to be used anywhere: vitalidze/chromecast-java-api-v2/issues/103

Anyhow, it should be possible to read the group members through a http request when first connecting to the group, then rely on the DEVICE_ADDED / DEVICE_REMOVED messages.

**Comment by balloob** [comment]
Ha, wow, this issue is from 2016 😱 

I think by now you know more about Chromecast API than I do, so I will join your lead.
