### ISSUE TITLE
Play notifications on Chromecast

### ISSUE THREAD

**Issue by igorzel** [balloob/pychromecast#123]
I have Chromecast Audio. It plays Google Play Music all the time.

From time to time I need to interrupt it and play small (<=10 seconds) mp3 files (notifications) on it. These files are hosted on server and I'm able to play them using pyChromecast and this very simple script:
`import pychromecast`
`cast = pychromecast.get_chromecast(friendly_name="Bedroom")`
`cast.wait()`
`mc = cast.media_controller`
`mc.play_media('http://SERVER_HOST/audio/GoodMorning.mp3', 'audio/mpeg')`

It works well and plays media file on Chromecast.

**My problem here:**
I want my Chromecast to resume playing Google Play Music after notification playback is done.
Is it possible to save current Chromecast casting source before **mc.play_media(...)** call and then start it again (as a simplest example: in 10 seconds)?

**Comment by balloob** [comment]
It's not possible right now. Every app has it's own way of getting setup and thus would need to be reverse engineered individually. On top of that not each backend might support re-opening a closed session.

**Comment by TheoHarbers** [comment]
I want to do the same thing using nodejs and node-red. After connecting to the chromecast but before start playing the notification i can see what is playing currently on the chromecast using the client.getStatus and also i get appId, sessionId, transportId, namespaces and volume. 

in the SDK there is cast.framework.RemotePlayer

savedPlayerState
nullable {mediaInfo: nullable chrome.cast.media.PlayerState, currentTime: number, isPaused: boolean}

With the following remark:
Remote player state saved when the session has disconnected. Can be used to continue playing locally from same location on disconnect event.

So i think it should be possible and needs further investigation.

**Comment by mungle** [comment]
Hello,
Old issue but I have the same problem. Did you find solutions?

I'm looking a way to resume what the Chromecast was playing before or better mix two audio inputs (Google Play Music/Spotify + notification). I hope someone can give me a suggestion.
Thank you
