### ISSUE TITLE
.pause() Works in python cmd line but not in when running as script

### ISSUE THREAD

**Issue by nmyster** [balloob/pychromecast#128]
Hi,

I am playing with this library and can't get pause to work in a script.
If I do:
```
from __future__ import print_function
import time
import pychromecast
cast = pychromecast.get_chromecast(friendly_name="Bedroom Chromecast")
# Wait for cast device to be ready
cast.wait()
print(cast.device)
print(cast.status)
mc = cast.media_controller
mc.pause()
time.sleep(5)
mc.play()
```

In a python cmd session, it works as expected. If I then put this into a .py file and run it, again it all works except for the mc.pause() part. There is no error output and the script appears to finish without issue.

Can anyone suggest what might be going on?

**Comment by dmn001** [comment]
I find that it works after sleeping 1 second after `cast.wait()`. So it does not seem to be ready immediately after that.

**Comment by armills** [comment]
I opened a PR with a fix. It adds a `wait` method to the media controller that can be included just before the call to `mc.pause()`.
