### ISSUE TITLE
Extra dependencies on raspbian Jessie (raspberry pi)

### ISSUE THREAD

**Issue by Frostlock** [balloob/pychromecast#132]
It works on raspberry pi (raspbian Jessie). Just make sure the following python packages are installed:

```
sudo apt-get install python-dev
sudo pip install netifaces
sudo pip install enum34
```

It might help someone else in the future. :-)

**Comment by balloob** [comment]
The dependencies should be installed as part of installing the package from pypi. (but yes, python-dev is needed for netifaces)

**Comment by Frostlock** [comment]
Well, pip did not do it for me so I figured something is wrong in the dependencies configuration. Pip just complained about netif aces when installing pychromecast.

**Comment by pointandyshoot** [comment]
I needed to install as described above to get it working for me on Raspbian Jessie lite. Thanks for making a note of it.
