### ISSUE TITLE
play .m3u file

### ISSUE THREAD

**Issue by alesms** [balloob/pychromecast#133]
Hi,
I use a library to create a playlist from my google play music account, but when i try to use it the stream doesn't work.
Is there a way to play a m3u file?

Thanks all

**Comment by balloob** [comment]
No, that's not a supported cast format

**Comment by Danielhiversen** [comment]
@alesms Did you find a way to play music from google music to chromecast?

**Comment by pmcelreavy** [comment]
@Danielhiversen @alesms Have you figured this out? I'm especially interested in integrating with GMusicProxy.
