### ISSUE TITLE
Is it possible to send media to a chrome cast "group"

### ISSUE THREAD

**Issue by strunker** [balloob/pychromecast#144]
I have seen a few other tickets relating to this, but cannot find any clear answer.

I know you can call play_media on a specific cast device, but is there a way to accomplish this via casting group? I had thought about calling play_media on cast device 1 then again on cast device 2 (on the next line of code) but that will likely introduce a delay that while minimal, would be noticeable. 

Thanks.

**Comment by paultag** [comment]
I can't remember if I did this with pychromecast or not, but I think it's able to stream to groups built in and there might even be an is_group boolean on the chromecast object

**Comment by strunker** [comment]
The only way I have personally been able to make this all work is to explicitly define my chromecast devices. Auto discovery and friendly name dont seem to be working for me on win 10 \py 2.7

So what I have to do instead is define things like

bedroom = pychromecast.Chromecast("10.x.x.x")
kitchen = pychromecast.Chromecast("10.x.x.x")

So not sure how I would translate the above to casting to a group.. Thats my confusion. If I could auto discovery devices by friendly names, perhaps the group name would be something that is advertised. 

Not sure how (under the hood) casting is done to the group of devices. If its some type of multicast that goes to both the chromecast devices at the same time, telling them to start playing at the same moment in time. 

I could, like I alluded to earlier, send the play_media command to one device at a time, but that will introduce a short delay in the play back. Seems rather inelegant.

**Comment by theychx** [comment]
> and there might even be an is_group boolean on the chromecast object

A Chromecast object has a `cast_type` attr. Docstring:
```
Returns the type of the Chromecast device.
This is one of CAST_TYPE_CHROMECAST for regular Chromecast device,
CAST_TYPE_AUDIO for Chromecast devices that only support audio
and CAST_TYPE_GROUP for virtual a Chromecast device that groups
together two or more cast (Audio for now) devices.
```
This would suggest that you adress a group of CC audio's in the same manner as you would adress a single CC. I have never tried it myself, as I do not have access to multiple CC audios.
Try doing a `get_chromecasts` and see if the group doesn't come up as a seperate entry. I bet it does.

**Comment by strunker** [comment]
yeah thats the sad part for me is get_chromecasts doesn't work for me. I guess its a bug in zeroconf thats what I have come to understand reading up on it.  

If I knew how the group casting worked underlying I could try to emulate that. I would imagine it is some type of multicast sending the play command to both devices in tandem. 

I read up in another one of the tickets submitted on the zeroconf bugged and someone had suggested making a config change to zeroconf. When I do get_chromecasts I receive an empty list returned so thats why I had to hard code the actual chrome cast devices by IP address.

**Comment by strunker** [comment]
So, regarding the above. I was able to fix zeroconf on windows 10 by doing the below.

In zeroconf.py comment out this line. The direction stated 1603, but I actually found it in a function starting on line 1438, the code had to be commented out in 1443.

This seems to ocurr in line 1603
if addr.get('netmask') != HOST_ONLY_NETWORK_MASK

In any event, once I did this I was a able to actually get a list of all my devices

Chromecast('10.1.1.13', port=8009, device=DeviceStatus(friendly_name=u'Strunker SoundBar', model_name=u'SmartCast Sound Bar 4551-D5', manufacturer=u'VIZIO', api_version=(1, 0), uuid=UUID('57b3b87b-2545-db3c-b30d-a28690b86ec6'), cast_type='cast'))

Chromecast('10.1.1.12', port=8009, device=DeviceStatus(friendly_name=u'StrunkerKitchen', model_name=u'Chromecast Audio', manufacturer=u'Google Inc.', api_version=(1, 0), uuid=UUID('99c3141d-6251-3bd3-c225-1110691224cc'), cast_type='audio'))

Chromecast('10.1.1.11', port=8009, device=DeviceStatus(friendly_name=u'Strunker', model_name=u'Chromecast', manufacturer=u'Google Inc.', api_version=(1, 0), uuid=UUID('eaaf6447-a0d3-8ed6-1d28-253e8f9f4f4b'), cast_type='cast'))

Chromecast('10.1.1.12', port=42236, device=DeviceStatus(friendly_name=u'GroupAudio', model_name=u'Google Cast Group', manufacturer=u'Google Inc.', api_version=(1, 0), uuid=UUID('87779a9e-6a3a-444e-bd6f-5a5355d67674'), cast_type='group'))
[Finished in 5.9s]

what I find somewhat interesting is the chromecast audio dongle i have in my kitchen which I statically set to 10.1.1.12 is the same ip that the groupaudio is associated with. The only different is port number....

I dont believe there is a way to specify port in pychromecast. Perhaps streams received on port 42236 are somehow recasted to all other devices that are part of the group? the chromecast audio dongle itself has to be somehow involved in the group cast since the traffic is being sent to it.

**Comment by strunker** [comment]
Tried to do the below. Set it to the groups ip (which is really just the audio dongle IP)

Tried to hard set the port to what is being advertised. 

Then tried to set the cast_type 

CC3 = pychromecast.Chromecast("10.1.1.12")
print dir(CC3)
CC3.port = 42236
CC3.cast_type="group"
print CC3.port
print CC3.cast_type
cast = CC3.media_controller
cast.play_media("http://10.1.1.2:8000/Filter - I'm not the only one.mp3",'audio/mp3')

I was able to set the port, but I wasnt able to set the cast type to group 

    CC3.cast_type="group"
AttributeError: can't set attribute

so back to square 1.

**Comment by theychx** [comment]
From Chromecast docstring:
```
:param port: The port to use when connecting to the device, set to None to
             use the default of 8009. Special devices such as Cast Groups
             may return a different port number so we need to use that.
```
So I would assume you would just do: `cast = pychromecast.Chromecast('10.1.1.12', port=42236)`
And I don't think you are meant to change those attributes post object creation.

**Comment by strunker** [comment]
CC3 = pychromecast.Chromecast("10.1.1.12")
print dir(CC3)
CC3.port = 42236
CC3.cast_type="group"
print CC3.port

specifying the port is what I did here.

I can try to set it during the actual object creation and see if it makes a difference when I set it after the fact it didnt error on setting the attribute which was good. Ill test and see if it makes a difference.

**Comment by strunker** [comment]
CC3 = pychromecast.Chromecast("10.1.1.12", port=42236)


#CC3.cast_type='group'
print CC3.port
print CC3.cast_type
cast = CC3.media_controller

so this is what the code looks like now, here is what it prints out

42236
audio
[Finished in 0.6s]

IT WORKS your way works of assigning the port during object creation as a param.

The weird thing is if I try to assign the port afterwards, I actually get a print out with the proper port, but it doesnt seem to matter, it still will only cast to one device.

CC3 = pychromecast.Chromecast("10.1.1.12")

CC3.port = 42236
#print CC3.cast_type

cast = CC3.media_controller
cast.play_media("http://10.1.1.2:8000/K.Flay - FML (Vanic Remix).mp3",'audio/mp3')

print CC3
**Chromecast('10.1.1.12', port=42236, device=DeviceStatus(friendly_name=u'StrunkerKitchen', model_name=u'Chromecast Audio', manufacturer=u'Google Inc.', api_version=(1, 0), uuid=UUID('99c3141d-6251-3bd3-c225-1110691224cc'), cast_type='audio'))
[Finished in 2.8s]**

**One other thing I did notice, when casting to the group.. 

the .stop() method .pause() etc no longer work.**

**Comment by strunker** [comment]
The only way I can terminate playback on the group is to call quit_app() on the actual chromecast object (in the above example CC3. 

calling stop \ pause methods on the media controller object have no impact. Kind of interesting.

**Comment by strunker** [comment]
Going to mark this resolved, and open a separate ticket concerning the issue with play back control, as that is likely a real bug.
