### ISSUE TITLE
Cast a local .PNG image

### ISSUE THREAD

**Issue by 1337sup3rh4x0r** [balloob/pychromecast#154]
Hi there,
I am trying to cast a .PNG image that resides in the same folder, I run the commands from.

However the following set of commands derived from the readme does not lead to the image being shown on the Chromecast, but only the generic gray screen with the blue Chromecast icon:

    >> from __future__ import print_function 
    >> import time 
    >> import pychromecast 
    >> chromecasts = pychromecast.get_chromecasts() 
    >> [cc.device.friendly_name for cc in chromecasts] 
    ['Dev', 'Living Room', 'Den', 'Bedroom'] 
    >> cast = next(cc for cc in chromecasts if cc.device.friendly_name == "Living Room") 
    >> cast.wait() 
    >> mc = cast.media_controller 
    >> mc.play_media('my image.png', 'image/png')

**Comment by armills** [comment]
The image needs to be accessible via a web protocol for the Chromecast to access. pychromecast just passes the URL to the Chromecast, it doesn't upload the file.

If you browse to the folder with `my image.png` you can start a [python simple server in that directory.](http://www.linuxjournal.com/content/tech-tip-really-simple-http-server-python) Try browsing to the image in your browser, then use that URL to send to the Chromecast.

**Comment by 1337sup3rh4x0r** [comment]
I think get it now, thanks!

I thought pychromecast would really stream the image.

Will try that out tonight
