### ISSUE TITLE
Avoid Chromecast loading url from cache

### ISSUE THREAD

**Issue by 1337sup3rh4x0r** [balloob/pychromecast#157]
Hi there,

I have managed to cast a picture to chromcast now with this script:

	from __future__ import print_function
	import time
	import pychromecast

	chromecasts = pychromecast.get_chromecasts()
	cast = next(cc for cc in chromecasts if cc.device.friendly_name == "CCK")
	cast.wait()
	mc = cast.media_controller
	mc.play_media('http://192.168.178.11/picture.png','image/png')
	mc.block_until_active()

I want to call this script every 60 seconds to update the picture. However on the chromecast screen the image does not change. It shows the same image as when I casted it the first time.

I I open the url from a browser, I can see that the image has actually been updated.

Ho do I make the chromecast always refresh the image?

**Comment by armills** [comment]
There's a good answer here: http://stackoverflow.com/a/29059407

Probably whatever server you're using is adding cache headers when it serves up the file. If you can't control the headers you can probably add a query string with extra values.
