### ISSUE TITLE
Behaviour of media_controller.block_until_active

### ISSUE THREAD

**Issue by theychx** [balloob/pychromecast#160]
@armills 
In relation to https://github.com/balloob/pychromecast/pull/145, I'm having a bit of a problem with `block_until_active`'s behaviour. For [this project](https://github.com/skorokithakis/catt), I need to be able to block until `media_controller` is ready but not necessarily playing. Before `0.8.0`, I could have used `update_status(blocking=True)`, but that does not seem to be available anymore. Any ideas?

For reference, see https://github.com/skorokithakis/catt/issues/12#issuecomment-276869698.

**Comment by armills** [comment]
@dominikkarall Might be able to answer better, since this was removed with #131. Can you link to your usage so I can understand it better? Can you make use of the update_status callback to achieve what you're trying to do?
