### ISSUE TITLE
[Help] How to use  it

### ISSUE THREAD

**Issue by varazir** [balloob/pychromecast#163]
Hello, I have been trying to google but can't find anything that gives my anything near I want. 

i want to monitoring my CC and if it's playing it do a URL call to http://adress.com/turn/off/device
When it stops playing it do another url call. 

I prefer running it on my rasperry pi 1 but I can use a Ubuntu server.  

TIA
Daniel

**Comment by balloob** [comment]
See https://github.com/balloob/pychromecast#how-to-use

**Comment by varazir** [comment]
Nothing more? 

It doesn't say me much...

**Comment by armills** [comment]
You didn't give any information about what you've done so far, so there's not much we can do to help you.

Honestly though, based on what you described you might as well just use [Home Assistant](https://home-assistant.io/). It already has capabilities to run automations based on chromecast status, and there's a lot more community support: https://home-assistant.io/help/

**Comment by varazir** [comment]
My bad, I'm running Domoticz on a Raspberry PI, I like to motionering the status of the chromecast and change switches.  Easiest way to do that is with url commands I think.

**Comment by Danielhiversen** [comment]
You can see how Home Assistant is doing it here: https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/media_player/cast.py

**Comment by armills** [comment]
OK, have you tried running the scripts that balloob linked? Does it work? Those instructions should show you how to read the current status of the chromecast. At that point it's up to you to integrate it into your system.

**Comment by varazir** [comment]
Thanks, I'll take a look it.

**Comment by varazir** [comment]
@armills @Danielhiversen 

Found this https://gist.github.com/varazir/13a611976b6e5d4811da83e1150295f5 

Getting errors shown in the gist as well.  

Installation:

gist clone  https://github.com/balloob/pychromecast.git
sudo apt-get install python3-dev python-dev
cd pychromecast
pip install -r requirements.txt
sudo python setup.py install
