### ISSUE TITLE
Listener receives strange player_state updates under certain circumstances

### ISSUE THREAD

**Issue by theychx** [balloob/pychromecast#168]
Howdy. Using this listener:
```
class MediaStatusListener:
    def __init__(self):
        self.playback_end = False

    def new_media_status(self, status):
        if status.player_state in ["UNKNOWN", "IDLE"]:
            self.playback_end = True
```
I am getting a strange series of statuses in this scenario:
+ Launch any non-google-namespace app
+ Initiate playback from that app
+ Initiate playback with `media_controller.play_media`
+ Call `block_until_active`
+ Register listener

The listener then receives the following `player_state` updates:
`PLAYING UNKNOWN IDLE BUFFERING PLAYING`

It would seem that `block_until_active` gets confused here and stops blocking prematurely. Or perhaps it is a bug in `play_media`, I cannot tell.

(using `PyChromecast 0.8.1`)

**Comment by armills** [comment]
block_until_active is only intended to block until the app is active. It's only necessary to ensure that playback commands (pause/stop/etc.) can be issued to the app. It's not intended to block until the the play_media command completes.

**Comment by theychx** [comment]
> block_until_active is only intended to block until the app is active

Yes, I realize that. The thing is, in this scenario, it stops blocking before the app is active.
Consider this:
```
cast = pychromecast.Chromecast('192.168.0.136')
cast.wait()
cast.media_controller.play_media('http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4', 'video/mp4')
cast.media_controller.block_until_active()
```
This code works if run when the cc is idle. It does not work if run when another app is playing something.

**Comment by theychx** [comment]
If I run the top example when the cc is idle, the listener gets these `player_state` updates:
`IDLE BUFFERING BUFFERING PLAYING` - which makes sense.

**Comment by armills** [comment]
OK, I took another look at this and refreshed my memory:

Right now we aren't doing any tracking of which app is running. We're just making sure that there is an active media session present. The original intended purpose of block_until_active is to allow control of a media session that was started externally.

https://github.com/balloob/pychromecast/blob/master/pychromecast/controllers/media.py#L411

I think for this situation you'll need to create your own threading event to block on. In your media listener, you can check that the app id matches what you're looking for, and set the event.

**Comment by theychx** [comment]
Thank you @armills, for this info.
