### ISSUE TITLE
Can't cast local file

### ISSUE THREAD

**Issue by woodyl** [balloob/pychromecast#181]
I'm trying to cast from a local file.  I can create a local server using Python3 http.server, but when I try to cast, nothing happens.  For example, I'm casting from 'http://127.0.0.1:8000/My_File.mp3'.  I can use curl to test that this location is serving the file, but it doesn't work with pychromecast.  I also tried using a similar server set up with ssl, but that didn't work either.

Does anybody have any suggestions about why this isn't working or else a code example of how to cast using Python http.server?

**Comment by armills** [comment]
127.0.0.1 is the localhost address, which points to your machine. You need to use the IP address of your machine on your local network. First make sure you can access the link from a different computer on your network before trying to cast.

**Comment by woodyl** [comment]
Oh, I should have thought of that!  Thanks much for your help.  That fixed it.
