### ISSUE TITLE
documentation for URNs used in the code

### ISSUE THREAD

**Issue by PraveenkumarDonga** [balloob/pychromecast#187]
Hi!
I am going through the code and there are some URNs being used.
NS_CONNECTION = 'urn:x-cast:com.google.cast.tp.connection'
NS_RECEIVER = 'urn:x-cast:com.google.cast.receiver'
NS_HEARTBEAT = 'urn:x-cast:com.google.cast.tp.heartbeat'

May I know how did you get these urns. Is there any documentation from google for theese.
if google releases the new version of chrome-cast sdk, still will it work?
or if changes are required where do we need to make the changes?
Looking forward for your help.

Thanks

**Comment by balloob** [comment]
Got these from looking at the data transmitted between Chrome and the Chromecast. See instructions how to do that in the [README](https://github.com/balloob/pychromecast#exploring-existing-namespaces).

Chances of Google breaking the Chrome Cast SDK are very very small as it is in TVs all over the world with a low chance of those getting updates.
