### ISSUE TITLE
How to cast entire desktop?

### ISSUE THREAD

**Issue by johnlinp** [balloob/pychromecast#189]
In your example codes, I see how media files and youtube videos can be played to chromecast. Is there a way to cast my entire desktop screen? I want a mirror display like [this](https://youtu.be/3U1DVkNPxsA?t=4m1s).

Is it possible to achieve this with current `pychromecast`? If not, can you give me any guide to implement it? Thank you!

**Comment by balloob** [comment]
That is not possible. I guess you'll have to reverse engineer the Cast screen share protocol to do that. Instructions how to look at the exchanged info is here: https://github.com/balloob/pychromecast#exploring-existing-namespaces

Closing the issue as it's not currently part of the focus of this lib.

**Comment by johnlinp** [comment]
Thanks a lot for your explanation!
