### ISSUE TITLE
Twitch Support ?

### ISSUE THREAD

**Issue by StarNab** [balloob/pychromecast#190]
Hi, 

This looks like what I need but I'm not sure if it is possible to start twitch live streams with this API ?
Can someone help ?

**Comment by StarNab** [comment]
@cjhutchi hi man, i gave a try to your fork but it doesn't seem to work. Maybe i'm doing something wrong ? Can you help ?

**Comment by balloob** [comment]
We currently do not support twitch.

**Comment by StarNab** [comment]
I tried the method to create my own controller. Is this still up to date ?
Searching for "Tr@n$p0rt" doesn't give any results
I searched for a json file request but couldn't find any

**Comment by 0187773933** [comment]
https://github.com/ytdl-org/youtube-dl
https://github.com/xat/castnow
```
castnow --address $ChromeCastIP `youtube-dl -g https://www.twitch.tv/chess`
```
