### ISSUE TITLE
Start live HLS at the end of the stream, not the beginning

### ISSUE THREAD

**Issue by lletourn** [balloob/pychromecast#192]
I'm trying to get the chromecast to play a live HLS stream not from second 0 but from where the "action" is right now.

The m3u8 doesn't contain the #EXT-X-ENDLIST (so it is live) and the header contains this:
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-ALLOW-CACHE:YES
#EXT-X-TARGETDURATION:6
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-PLAYLIST-TYPE:EVENT

Why does it always start at the beginning?
I tried seeking (status says 'supports_seek': True)

I tried 
mc.play_media(<URL>, 'application/x-mpegurl', stream_type='LIVE')

neither worked

any ideas?

Thank you

**Comment by Steve132** [comment]
BUMP I also have this problem.

**Comment by lletourn** [comment]
I was actually able to "fix" it.
Seeking originally didn't work, but if you set "stream_type='LIVE'" when calling cast.media_controller.play_media
then wait 2-5secs
and then call cast.media_controller.seek(999999)

it seemed to work for me.

I originally expected that just setting stream_type live would do it, but it doesn't

**Comment by Steve132** [comment]
Unfortunately, when I set stream_type="LIVE" my stream doesn't even
oen...but I'll try this.
