### ISSUE TITLE
CAST_TYPES dict lacks some cast models

### ISSUE THREAD

**Issue by OttoWinter** [balloob/pychromecast#201]
While looking for the culprit for pychromecast breaking with 1.0.2, I have found that some cast devices are not assigned the correct cast type. More precisely, the dictionary in [dial.py](https://github.com/balloob/pychromecast/blob/master/pychromecast/dial.py#L23), that is meant to resolve model names to their corresponding CAST_TYPE [here](https://github.com/balloob/pychromecast/blob/master/pychromecast/dial.py#L71), doesn't include all model name to cast_type mappings. For example, my Google Home Mini reports a `model_name` of "Google Home" and my Chromecast v1 "Eureka Dongle", but none of these keys are in the mapping. This results in pychromecast incorrectly assuming audio-only devices like the Google Home to be the default type (a video+audio chromecast).

This should essentially be an easy fix, since it only involves adding/changing some of the keys in the mentioned mapping - and I would be happy to create a PR. But in order to find the correct mappings, I need some assistance because currently only my Google Home Mini and Chromecast v1 are operational. So if somebody wants to help, just enter http://CAST_IP:8008/setup/eureka_info?options=detail in your browser and report your "model_name" together with the device type (video+audio, or audio-only).

P.S. This issue actually seems to have been around for quite a while. Even the old way of using "/ssdp/device-desc.xml" returned invalid modelNames.

**Comment by basschipper** [comment]
I only have these devices:
"model_name": "Chromecast Audio" (audio-only)
"model_name": "Google Home" (audio-only)

**Comment by theychx** [comment]
Chromecast v2 is the same as v1.
