### ISSUE TITLE
Feature Request: Support for accountId / user from CastStatus

### ISSUE THREAD

**Issue by mjmaurer** [balloob/pychromecast#205]
Is it possible to get some sort of user identifier for a given cast?

Either the Google account casting or user logged in with the media application

**Comment by balloob** [comment]
No. There is no such thing in the Cast protocol. One can cast a video without an account.

**Comment by ssieb** [comment]
There must be something because there's a little popup when someone connects to the Chromecast showing their name and picture.  Or is that only for a specific application like youtube?
