### ISSUE TITLE
mpeg stream

### ISSUE THREAD

**Issue by amarco** [balloob/pychromecast#207]
I have a web url (http://localhost:5000) hosted by a flask webserver in python for example that when I point my google chrome browser it streams the animated jpeg as expected but if I use pychromecast to cast the url (  mc.play_media('http://localhost:5000', 'image/jpeg') ) I get nothing but a chromecast icon in the middle of the television.
Any thoughts why this might be?
Marco

**Comment by minektur** [comment]
"localhost" to the chromecast is the device itself.  The web-browser that
displays on your screen is running on the chromecast device.  You need to
make your app listen on the IP of whatever computer is running your python
flask app, and then have the chromecast  play '
http://your.ip.address.here:5000'   and also make sure that you've opened
that port on your firewall so that external machines can see it.

**Comment by amarco** [comment]
Thanks minektur
Good point about what localhost means to the chromecast dongle.
My server is listening on all ports ( webserver.run(host='0.0.0.0',threaded=True))
and when I change the chormecast to explicit address [mc.play_media('http://gue-w10n-ma.rwdigroup.net:5000', 'image/jpeg') ]. I still get the same problem, little blue chromcast icon in middle of tv.
Also comments on firewall are fair, but firewall is disabled :(
Marco

**Comment by minektur** [comment]
The first thing to check is to make sure another computer on the local
network can get to that URL just using a regular browser. You can think of
the Chromecast device as just another computer with a browser on your
network. If that works then the only thing I can think of is maybe you
aren't using a supported media format. That's a long shot though.

**Comment by amarco** [comment]
Well I had thought of that possibility and I did confirm the web page is visible from a totally different machine while it is not visible on the tv. 
I also confirmed that I can cast to the tv directly via a browser just not via pychromecast.
At this point I am somewhat puzzled where the problem lies. Any thoughts would be helpful. 
The output in the python console does not indicate any errors , snippet follows:
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
10.212.110.103 - - [04/Jan/2018 20:24:39] "GET / HTTP/1.1" 200 -
10.212.110.103 - - [04/Jan/2018 20:24:39] "GET /video HTTP/1.1" 200 -
10.212.110.103 - - [04/Jan/2018 20:24:39] "GET /favicon.ico HTTP/1.1" 404 -
<MediaStatus {'metadata_type': None, 'title': None, 'series_title': None, 'season': None, 'episode': None, 'artist': None, 'album_name': None, 'album_artist': None, 'track': None, 'subtitle_tracks': {}, 'images': [], 'supports_pause': True, 'supports_seek': True, 'supports_stream_volume': True, 'supports_stream_mute': True, 'supports_skip_forward': False, 'supports_skip_backward': False, 'current_time': 0, 'content_id': 'http://10.10.32.212:5000', 'content_type': 'image/jpeg', 'duration': None, 'stream_type': 'BUFFERED', 'idle_reason': None, 'media_session_id': 1, 'playback_rate': 1, 'player_state': 'IDLE', 'supported_media_commands': 15, 'volume_level': 1, 'volume_muted': False, 'media_custom_data': {}, 'media_metadata': {}, 'current_subtitle_tracks': []}>
Press any key to continue . . . 10.10.32.158 - - [04/Jan/2018 20:24:45] "GET / HTTP/1.1" 200 -
INFO:werkzeug:10.10.32.158 - - [04/Jan/2018 20:24:45] "GET / HTTP/1.1" 200 -
10.10.32.158 - - [04/Jan/2018 20:24:47] "GET / HTTP/1.1" 200 -
INFO:werkzeug:10.10.32.158 - - [04/Jan/2018 20:24:47] "GET / HTTP/1.1" 200 -
10.212.110.103 - - [04/Jan/2018 20:25:56] "GET / HTTP/1.1" 200 -
INFO:werkzeug:10.212.110.103 - - [04/Jan/2018 20:25:56] "GET / HTTP/1.1" 200 -
10.212.110.103 - - [04/Jan/2018 20:25:56] "GET /video HTTP/1.1" 200 -
INFO:werkzeug:10.212.110.103 - - [04/Jan/2018 20:25:56] "GET /video HTTP/1.1" 200 -

Notes: 
10.212.110.103 is a remote machine running google chrome which displays correctly,
10.10.32.158 is the actual chromecast ip address
10.10.32.212 is the ip address of the computer running the python code below.

For interest the complete code (requires a web cam) is below and used python >3.5:

from __future__ import print_function
from flask import Flask, render_template_string, Response
import cv2
import pychromecast
import pychromecast.controllers.dashcast as dashcast
from threading import Thread

webserver = Flask('Biker')
camera = cv2.VideoCapture(0)          

def frame():
    _, image = camera.read()
    _, jpeg = cv2.imencode('.jpg',image)
    img=bytes(jpeg)
    outFrame = b'' 
    outFrame += b'--frame\r\n'
    outFrame += b'Content-Type: image/jpeg\r\n\r\n'   
    outFrame += img
    outFrame += b'\r\n'
    return outFrame

@webserver.route('/')
def index():
    return render_template_string('''
<!doctype html>
<html>
 <head>
  <title>Ghost Cast - Bike View</title>
 </head>
 <body>
  <h1>Video View</h1>
  <img src="{{ url_for('video') }}" height="480" width="640">
 </body>
</html>
''')

def genFrames():
    while (True):
        yield frame()

@webserver.route('/video')
def video():
    return Response(genFrames(), mimetype='multipart/x-mixed-replace; boundary=--frame')

def startWebServer():
    webserver.run(host='0.0.0.0',threaded=True)


if __name__ == '__main__':
    webThread=Thread(target=startWebServer)
    webThread.start()
    
    device_friendly_name = "BikeCast"
    chromecasts = pychromecast.get_chromecasts()
    cast = next(cc for cc in chromecasts if cc.device.friendly_name == device_friendly_name)
    cast.wait()
   
    mc = cast.media_controller
    mc.play_media('http://10.10.32.212:5000', 'image/jpeg')
    mc.block_until_active()
    print(mc.status)
    mc.play()

**Comment by amarco** [comment]
turns out I need to be explicit and send the exact url of the mjpeg stream to the chromecast controller where as the browser was happy with the webb page itself which contained the mjpeg link. Once I changed:
mc.play_media('http://10.10.32.212:5000', 'image/jpeg') 
to 
mc.play_media('http://10.10.32.212:5000/video', 'image/jpeg') 
all started to work as expected. 
Thanks for listening to my process and your suggestions.
Marco

**Comment by ssieb** [comment]
It looks like you're giving the Chromecast the wrong url.  The root is the web page which it can't display. Give it the /video path which is the jpeg stream.

**Comment by ssieb** [comment]
Funny, we both posted at the same time.  Good to see you figured it out.
