### ISSUE TITLE
get_chromecasts() no connection on Windows 10/Server 2016

### ISSUE THREAD

**Issue by d8ahazard** [balloob/pychromecast#208]
Greetings,

So, I'm running into a rather big issue in creating a plugin for Plex Media Server to be able to interact with cast devices headlessly. 

On Linux, my implementation works perfectly. Cast devices are discovered and cached, and I'm about to get ready to work on a playback implementation.

However, on Windows, it fails to find any devices - both inside my Plex Plugin implementation, as well as directly through the python console using pip imports.

Originally, I had some virtual adapters in play for Hyper-V, but even after removing them, verifying WIndows Firewall was off, etc. - it doesn't connect. Specifically, in the py console, I'm seeing "pychromecast.socket_client:Failed to connect, retrying in 5.0s" on trying to discover devices. In the Plex plugin, it just doesn't find anything.

What's interesting is that in Plex, if I wireshark my connection for UDP on 5353, I can see both the outgoing query form the server, as well as the responses from my cast devices on the LAN. However, it seems like pyChromeCast is not binding properly to the socket to listen for responses?

I'm no expert in any of this stuff, but I do have a PHP app that does cast discovery, and I recall having to work out a similar issue between Linux and windows where setting the SO_REUSEADDR or SO_REUSEPORT flags in the right sequence was necessary in order to get Windows discovering.

However, that didn't work here, and as I said, I'm at a loss. I'll continue poking around at things, but I'm very new to python, so I'm not as adept at messing with stuff.

Any other information I can provide - just let me know. Plex uses python 2.7 for it's core, I believe, and the console version I'm testing with is v3...

Also tested on my laptop running windows 10, it also failed to discover any devices in Plex - and discovery takes a looooong time before returning an empty array.

**Comment by OttoWinter** [comment]
Might be related to #209 and I was now able to replicate this issue on a Windows machine. Thank you very much for this information!

**Comment by d8ahazard** [comment]
Fwiw, I've found there was another issue, it really involves the sequencing
of the wrap SSL command. If you fire that after you connect the socket, it
seems to fix all issues.

Got some other stuff going on right now, but I plan on submitting a proper
pull request to get it fixed for everyone.

**Comment by OttoWinter** [comment]
You fixed this in #212, right? (Thanks, btw)

**Comment by d8ahazard** [comment]
Works for me!  😁

**Comment by d8ahazard** [comment]
Oh yeah, fixed in #212.
