### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by mahomat** [balloob/pychromecast#219]
Hi

I just reinstalled my raspberry and now when I try to setup the pychromecast I get an attribute error

 chromecasts = pychromecast.get_chromecasts()
AttributeError: 'module' object has no attribute 'get_chromecasts()

I used gitclone and in Pychromecast folder i ran "sudo pip install -r requirements.txt" with no problems.

Requirement already satisfied: requests>=2.0 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
Requirement already satisfied: protobuf>=3.0.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2))
Requirement already satisfied: zeroconf>=0.17.7 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 3))
Requirement already satisfied: six>=1.9 in /usr/lib/python2.7/dist-packages (from protobuf>=3.0.0->-r requirements.txt (line 2))
Requirement already satisfied: setuptools in /usr/lib/python2.7/dist-packages (from protobuf>=3.0.0->-r requirements.txt (line 2))
Requirement already satisfied: netifaces!=0.10.5 in /usr/local/lib/python2.7/dist-packages (from zeroconf>=0.17.7->-r requirements.txt (line 3))

Going crazy here knowing It worked perfect on my other 2 devices..

**Comment by mahomat** [comment]
This is the test script Im trying to run

from __future__ import print_function
import time
import pychromecast

chromecasts = pychromecast.get_chromecasts()
[cc.device.friendly_name for cc in chromecasts]
['Dev', 'Living Room', 'Den', 'Bedroom', 'Daniel Chrome']

cast = next(cc for cc in chromecasts if cc.device.friendly_name == "Daniel Chrome")
# Wait for cast device to be ready
cast.wait()
print(cast.device)
#DeviceStatus(friendly_name='Daniel Chrome', model_name='Chromecast', manufacturer='Google Inc.', uuid=UUID('df6944da-f016-4cb8-97d0-3da2ccaa380b'), cast_type='cast')

print(cast.status)
#CastStatus(is_active_input=True, is_stand_by=False, volume_level=1.0, volume_muted=False, app_id=u'CC1AD845', display_name=u'Default Media Receiver', namespaces=[u'urn:x-cast:com.google.cast.player.message', u'urn:x-cast:com.google.cas$

mc = cast.media_controller
mc.play_media('http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4', 'video/mp4')
mc.block_until_active()
print(mc.status)
MediaStatus(current_time=42.458322, content_id=u'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4', content_type=u'video/mp4', duration=596.474195, stream_type=u'BUFFERED', idle_reason=None, media_sessio$

# mc.pause()
# time.sleep(5)
# mc.play()

**Comment by theychx** [comment]
Pychromecast no longer supports python 2.
This would work:
```pip install PyChromecast==1.0.3 zeroconf==0.19.1```

Alternatively, there's [pychromecast_legacy](https://github.com/d8ahazard/pychromecast_legacy) (I haven't tested this).

**Comment by mahomat** [comment]
Ran `pip install PyChromecast==1.0.3 zeroconf==0.19.1` without problems and still get error.

Tried  pychromecast_legacy too but its the same error

**Comment by OttoWinter** [comment]
Does the script you're trying to run have the filename `pychromecast.py`? Additionally, do you maybe have a file called `pychromecast.py` lying around somewhere?

If you have such a file somewhere, then python will load the content of that file instead of the pychromecast library when you type `import pychromecast`

**Comment by mahomat** [comment]
Oh fu**...
Shuld have seen that myself :P 
Yes I had a folder named pychromecast from when I installed the files. 
Just removed it and everything worked like before!

Thanks for the quick respons tho. Saved me from going insane.

Have a nice weekend guys :D
