### ISSUE TITLE
wheel probably should be listed in requirements.txt

### ISSUE THREAD

**Issue by jsung** [balloob/pychromecast#229]
wheel probably should be listed in requirements.txt.

**Comment by balloob** [comment]
No. Wheel is not needed to use pychromecast.

**Comment by jsung** [comment]
In a virtual environment (i.e., "virtualenv" or "venv"), you do.  If not in requirements.txt, maybe in documentation somewhere.

Also, for a virtual environment, one needs to install python<version>-dev.  This is system wide.
