### ISSUE TITLE
TVHeadend streaming?

### ISSUE THREAD

**Issue by francoism90** [balloob/pychromecast#233]
Anyone have success with HTS streaming (e.g. `http://hts:password@<ip>:9981/stream/channelnumber/1`)?
I'm trying to stream, but it doesn't play it unfortunately. On my other (local) PC's it works fine.

```
Media status <MediaStatus {'metadata_type': None, 'title': None, 'series_title': None, 'season': None, 'episode': None, 'artist': None, 'album_name': None, 'album_artist': None, 'track': None, 'subtitle_tracks': {}, 'images': [], 'supports_pause': True, 'supports_seek': True, 'supports_stream_volume': True, 'supports_stream_mute': True, 'supports_skip_forward': False, 'supports_skip_backward': False, 'current_time': 0, 'content_id': 'http://hts:password@<ip>/stream/channelnumber/1', 'content_type': 'video/mp4', 'duration': None, 'stream_type': 'BUFFERED', 'idle_reason': None, 'media_session_id': 1, 'playback_rate': 1, 'player_state': 'IDLE', 'supported_media_commands': 15, 'volume_level': 1, 'volume_muted': False, 'media_custom_data': {}, 'media_metadata': {}, 'current_subtitle_tracks': [], 'last_updated': datetime.datetime(2018, 4, 24, 19, 26, 42, 542747)}>

Playing media
```

Thanks.

**Comment by OttoWinter** [comment]
My first guess would be that the Chromecast default media receiver app doesn't support "hts streaming". Quick question: What is HTS? I only know HLS/DASH streaming&manifests and a quick Google search only showed a TV station called HTS.

pychromecast is essentially just saying to the chromecast: play the content in this URL/string and just passes the raw string directly to the chromecast default media receiver. If that receiver doesn't support HTS streaming, then the media won't play. Another thing I would guess that the default media receiver doesn't support is URL-encoded authorization like `hts:password`.

Unfortunately, if the default media receiver doesn't support HTS streaming there's little you can do to fix the problem short of creating a new cast app (I tried for an old project, but it was just extremely difficult and kind of poorly documented)

**Comment by francoism90** [comment]
@OttoWinter Sorry, HTS is short for TVHeadend. It uses `MPEG-TS Pass-thru` for streaming, although other profiles can also be selected. Unfortunately non seem to work with Chromecast.

I will try to test non authenticate URL's, but if I'm not mistaken; it does support internal streaming, right? :)
