### ISSUE TITLE
Chromecast receiver

### ISSUE THREAD

**Issue by cadavre** [balloob/pychromecast#252]
Hi, first of all – sorry, just because I quite don't get what `spotify_example.py` can be used for.

I'm looking for creating a new discoverable Chromecast device (a receiver) with Python. I want it to be discoverable by, for example, Google Home, so it can be connected to and then receiving messages.

Is it even possible with `pychromecast`?

I can see everywhere we're using `chromecasts = pychromecast.get_chromecasts()` to get already-existing Chromecasts. Can i create a new one on my own?

If not with `pychromecast`, are there any other solutions out there?

**Comment by balloob** [comment]
PyChromecast is only a client for ChromeCasts, it cannot simulate one.
