### ISSUE TITLE
launch_app() hangs

### ISSUE THREAD

**Issue by AnsgarSchmidt** [balloob/pychromecast#253]
Hi,
I try to use spotify with pychromecast, after changing the code I get the spotify authorization to work but the sp.launch_app() hangs without any error or progress.

The code I used:
token         = util.prompt_for_user_token(USER, PERMISSIONS, client_id=CLIENT_ID , client_secret=CLIENT_SECRET, redirect_uri='http://localhost')
client        = spotipy.Spotify(auth=token)
sp            = SpotifyController(token)
cast         = pychromecast.get_chromecasts(timeout=10)[0]
cast.register_handler(sp)
sp.launch_app()

Thanks
Ansgar

**Comment by Tsjippy** [comment]
I have the same problem, I hope this can be resolved!

**Comment by Tsjippy** [comment]
@am0s , @rmkraus , @balloob 

Can you guys indicate whether you are still supporting pychromecast?

I see that the latest change is several months ago

**Comment by Tsjippy** [comment]
O, I checked it. The Spotify app starts, but says there is a connection problem, then exits.
sp.launch_app() does not know that Spotify has closed.

I use this scope: SCOPE = 'playlist-read-private playlist-modify-public playlist-modify-private playlist-read-collaborative user-read-private user-read-birthdate user-read-email user-read-playback-state user-read-currently-playing user-modify-playback-state app-remote-control streaming user-follow-modify user-follow-read user-top-read user-read-recently-played user-library-read user-library-modify'

**Comment by uudruid74** [comment]
I had a similar problem where spotify worked on smart speakers, but not on my Smart Display.  The difference was that a display fetches an ad and I have ads blocked.  You might want to check and make sure you have no ad-blockers on your network or whitelist the spotify domain

**Comment by Tsjippy** [comment]
I have it on all my devices, including a home mini

**Comment by Daquaney** [comment]
I am having the same problem, casting to youtube works like a dream but Spotify says there is a connection problem and then exits.

**Comment by emontnemery** [comment]
@Tsjippy How did you see that the app exited due to connection problem?

**Comment by Tsjippy** [comment]
I tried to open Spotify on my Chromecasts, I saw Spotify loading, then displaying "there is a connection problem" then exiting back to the backdrop

**Comment by emontnemery** [comment]
@Tsjippy Ah, but you didn't see anything on the pychromecast side except for the hang?

**Comment by emontnemery** [comment]
The hang is because the lack of timeout in launch_app, @fondberg can you shed light on if we can do something more intelligent? Otherwise, there should at least be a timeout.
https://github.com/balloob/pychromecast/blob/17eb885097da7b2b2418f909e2f23058245be72c/pychromecast/controllers/spotify.py#L38-L51

**Comment by fondberg** [comment]
I think we could check for the cast status but I'm not an expert on googles chromecast api. A timeout seems fair but I think it probably should be lower than 10 secs
