### ISSUE TITLE
Error communicating with socket, resetting connection

### ISSUE THREAD

**Issue by ngknick** [balloob/pychromecast#254]
Hi, I'm on hassio on a pi 3 - and have had pychromecast setup for a year or so. I've had these errors for months, and also not be able to send TTV to the google homes .... any ideas? Sorry, total noob at coding. But I can troubleshoot! 

Failed to connect. No retries.
5:09 PM /usr/local/lib/python3.6/site-packages/pychromecast/socket_client.py (ERROR)
Failed to connect, retrying in 5.0s
5:09 PM /usr/local/lib/python3.6/site-packages/pychromecast/socket_client.py (ERROR)
Error communicating with socket, resetting connection
5:09 PM /usr/local/lib/python3.6/site-packages/pychromecast/socket_client.py (WARNING)
Error reading from socket.
5:09 PM /usr/local/lib/python3.6/site-packages/pychromecast/socket_client.py (ERROR)
Error reading from socket.
5:00 PM /usr/local/lib/python3.6/site-packages/pychromecast/socket_client.py (ERROR)

**Comment by emontnemery** [comment]
@ngknick those prints just mean the connection to the chromecast was lost for whatever reason (the chromecast rebooted by itself, you turned it off, WiFi is unstable etc).

**Comment by metal3d** [comment]
I also have the same problem. My connection is not unstable and chromecast is working well with others streaming software (youtube, spotify, chrome tab...)
The source code is:

```python
import pychromecast

chromecasts = pychromecast.get_chromecasts()
[print(cc.device.friendly_name) for cc in chromecasts]

cast = next(cc for cc in chromecasts if cc.device.friendly_name == "Télé du salon")
cast.wait()
print(cast.device)
```

Running:
```
Polo
Gertrude
Télé de la chambre
Télé du salon
[192.168.1.16:8009] Failed to connect, retrying in 5.0s
```

And it waits forever...

**Comment by metal3d** [comment]
Version: PyChromecast==4.1.0
