### ISSUE TITLE
casting mkv file to chrome

### ISSUE THREAD

**Issue by forjin** [balloob/pychromecast#26]
Hi,

I am very pleased to have pychromecast. But I want to report some more feature on pychromecast for it's additional feature.

My scenario is like this.
1. I have no chrome browser but I can install some module in the server
2. I have some media file which is various format such as (.mkv, .avi) 

Problem.
I want to cast my mkv and avi file with out trascoding. 
If  it's not possible, I would like to cast during transcording.

Can I do this?

**Comment by balloob** [comment]
Marked it as a wontfix.

The goal for PyChromecast is to offer a library that implements the Google Cast protocol. Transcoding and serving video is therefore out of the scope of this project.
