### ISSUE TITLE
Spotify doenst work anymore...

### ISSUE THREAD

**Issue by maschhoff** [balloob/pychromecast#264]
Hi,

The spotify token is outdated.
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://accounts.spotify.com/api/login
See https://github.com/enriquegh/spotify-webplayer-token/issues/1 
So it does not work here anymore.
This is maybe a solution: https://stackoverflow.com/questions/53771382/requests-exceptions-httperror-400-client-error-bad-request-for-url-https-ac
Can someone please update it?
It was so great to use!

Thanks!

**Comment by shahinghazinouri** [comment]
Same issue...Spotify is broken.

**Comment by Nojahhh** [comment]
Hey guys,

I am also experiencing this.
This has been an issue for the last couple of months. (see [](https://github.com/balloob/pychromecast/pull/239))
Ever since Spotify reworked their authentication process and their removal/rework(?) of scopes, I've been hitting the wall.
Very interesting link though. I will try it with my installation and see if I can get something to work.

Would be nice to hear something from @balloob regarding this matter!

Thanks!

**Comment by maschhoff** [comment]
Hi,

till we have a solution I helped myself out by adapting a sctipt to make a radiostation of my Spotify-Client with Pulseaudio and VLC. Am am running this on a Linux VM on my Homeserver.
https://gist.github.com/maschhoff/5c78634825f2798e851cd16499a1fcf4 
For Windows you can use Streamwhatyouhear.com as well

Hope we´ll have something soon!
Thanks!

**Comment by fondberg** [comment]
@balloob is this something you mind if I have a go at? I need it for my spotify-card in lovelace so it can initiate spotify on a chromecast device. I have some insights into this

**Comment by emontnemery** [comment]
@fondberg A PR fixing the issue would be most welcome.

**Comment by fondberg** [comment]
I created one here: https://github.com/balloob/pychromecast/pull/275

**Comment by sblantipodi** [comment]
Since recent updates I have this error in the log
Not passing an entity ID to a service to target all entities is deprecated. Update your call to media_player.play_media to be instead: entity_id: all

**Comment by emontnemery** [comment]
@sblantipodi That really sounds like something Hass related, please ask for help in Hass forum or discord.

**Comment by emontnemery** [comment]
Fixed by #275
