### ISSUE TITLE
Speaker group Spotify not working

### ISSUE THREAD

**Issue by fondberg** [balloob/pychromecast#292]
It doesn't seem to be possible to start Spotify with playback on a chromecast speaker group `    "cast_type": "group"` using the `spotify_example.py`. Do I need to use the multizone code to achieve this?

**Comment by fondberg** [comment]
ping @emontnemery

**Comment by emontnemery** [comment]
@fondberg The point of the multizone code is just to keep track of which players are in which groups.
When using the `spotify_example.py` with a group, the Spotify app seems to launch successfully: the "start cast sound" is played by the group members, and the Google Home apps says that the group is casted to with Spotify.

The problem might be with spotipy, once this code is done, device_id is None:
```python
    for device in devices_available['devices']:
         if device['name'] == CAST_NAME:
             device_id = device['id']
             break
```

**Comment by fondberg** [comment]
@emontnemery I tested a little more and unfortunatly I think you are correct, the problem must be ub spotify (the least maintained library on github, last PR merged was oct -17). 
Thanks for the feedback and I'll keep you updated on that I find

**Comment by phr0z** [comment]
Hi,

I think spotipy only returns a list of available devices through this Spotify API
https://api.spotify.com/v1/me/player/devices 
https://developer.spotify.com/console/get-users-available-devices/

So if the app is launched properly on the Chromecasts group Spotify should register these devices and return this value.

I did see that when starting the cast from my iPhone the device_id returned from Spotify API is in caps whilst regular devices values are returned in lower cases.

Might it be that the namespace differs?

**Comment by fondberg** [comment]
@phr0z interesting, I only checked with what I got back from spotipy and yes it only returns devices from that endpoint.
What we need is the spotify device id so if you found which API endpoint from spotify the iOS app spoke to we can reverse engineer it.

**Comment by phr0z** [comment]
I used this code to retrieve the following;

code:
`import logging
import sys
import time

import pychromecast
from pychromecast.controllers.spotify import SpotifyController
import spotify_token as st
import spotipy

device_id = None
device_name = None

data = st.start_session("myspotifyusername", "myspotifypassword")
access_token = data[0]
expires = data[1] - int(time.time())

client = spotipy.Spotify(auth=access_token)

sp = SpotifyController(access_token, expires)

devices_available = client.devices()
print("devices found:", devices_available)
`

result:
`root@plex:/librespot/target/release# python3 spotify_refresh_devices.py
devices found: {'devices': [{'id': 'xvbny', 'is_active': False, 'is_private_session': False, 'is_restricted': False, 'name': 'DESKTOP', 'type': 'Computer', 'volume_percent': 41}, {'id': 'xbzvy', 'is_active': False, 'is_private_session': False, 'is_restricted': False, 'name': 'iPhone', 'type': 'Smartphone', 'volume_percent': 100}, {'id': 'ABCDEFGHIJ1234', 'is_active': True, 'is_private_session': False, 'is_restricted': False, 'name': 'MultiRoom', 'type': 'CastAudio', 'volume_percent': 100}]}
`

Note that Im running this while Im playing on my group initiated by Spotify app on iPhone. (Spotify drops the devices pretty quickly if they're not being used)

There's also the possiblity to start casting from play.spotify.com with Chrome web browser. That would allow for some additional debugging.

MultiRoom is infact my group and it's not listing any other single chromecast devices.

I'll keep digging and see what else I can find.

**Comment by phr0z** [comment]
Some data captured from Wireshark when initiating a cast to my group from Spotify iPhone app. 

The device_id registered in Spotify is based on the mdns reply. Sorry for the red-out. 
Basically the red-out aread contains an "id/guid/whatever" which is the one https://api.spotify.com/v1/me/player/devices returns. 
[https://imgur.com/a/Gakm3Am](url)

**Comment by phr0z** [comment]
I think I actually solved it.

Will upload example soon. :-)

**Comment by phr0z** [comment]
example here: https://github.com/phr0z/pychromecast/blob/master/examples/spotify_example_group.py

It does seem like it initializes another application in fact 531A4F84

For now I only seem to be able to playback single tracks uri's. It throws an error when i specify playlist uri.
Might be spotipy, too tired to continue right now. :-)

Please try.

**Comment by fondberg** [comment]
wow! Cool i'll try!

**Comment by fondberg** [comment]
I'm reopening this because I think we can add this functionality without Spotify help

**Comment by phr0z** [comment]
Hi,

Yes using my script and also Chrome browser it seems that way. "Master device" can change between my Chromecasts. But it will be the device witch uses the new app id.

Simple way for you to verify this is to try with Chrome browser, go to http://play.spotify.com
Then fetch your current running app_ids on your Chromecasts.

If I understand you correctly this is not the case for you when you use my script? I mean it doesnt always launch 531A4F84 on one of your devices?

This is the output i get with either my script or Spotify launched and casted from Chrome.
current_launched_apps
after_cc_device_id: Sovrum
after_cc_app_id: 705D30C6
after_cc_device_id: Vardagsrum
after_cc_app_id: 531A4F84
after_cc_device_id: MultiRoom
after_cc_app_id: CC32E753
after_cc_device_id: Kok
after_cc_app_id: 705D30C6
master_device: Vardagsrum

**Comment by phr0z** [comment]
Im speculating in that the reason _.app_id() returns "None" might have something to do with the how the session is handled. You can't really run it outside the scope of your application.

**Comment by emontnemery** [comment]
The example from @phr0z is a good start, but I think it's better to check group membership instead of app id, it seems a bit error prone in case several family members are casting at the same time.

> Question though: is there a way to get more information on a device with cast_type='group'? Can I get its individual devices?

Yes, that's the point of the multizone stuff.
Here's an example for how to do just that that:
https://github.com/balloob/pychromecast/blob/master/examples/multizone_example.py
With this, we can see if the cast Spotify reports in the API is a member of the group we want to play to, although just by name.

Checking group membership only is enough: If one group member is playing individually while the group is also active, a unique dynamic/temporary group excluding the individually playing group is formed. The temporary group has the same name, but a different UUID.
Just checking app id seems a bit error prone in case several family members are casting at the same time.

It's error prone to match on player _name_, cast allows multiple devices to have the same name, and the casts have a UUID to distinguish them.
@fondberg Any idea how the `id` in the `v1/me/player/devices response` is derived?

**Comment by phr0z** [comment]
the spotify id in devices is derived from mdns name. check my imgur above.

**Comment by emontnemery** [comment]
@phr0z Would you mind you explaining _how_ it's derived? Your image seems to have all the juicy bits censored and you're not mathcing spotify id with cast mdns data in your example either.

**Comment by phr0z** [comment]
I dont think anyone but Spotify themselves know exactly how it's derived. The API is not transparent.

A qualified guess would be a simple extract of the ID string in the MDNS record (TXT,SRV or PTR don't remember off the bat) which is not the same as the UUID which pychromecast gets. UUID contains dashes while the ID in the MDNS record is just one long identifier.

I do agree that it would be better to match directly against the id and to do so we need pychromecast to extract this ID value from the MDNS records.

**Comment by emontnemery** [comment]
@phr0z ok..

Anyway, will you update your example to check group membership for a better guess of which cast to cast to?

@fondberg do you suggest anything but an example is added to PyChromecast?

**Comment by phr0z** [comment]
Sure I can add a check for that with the help of 
`if` _device.cast_type == 'group'` :)

**Comment by emontnemery** [comment]
I meant to check group **membership** as outlined here: https://github.com/balloob/pychromecast/issues/292#issuecomment-491174814

**Comment by fondberg** [comment]
I think we don't need to update anything but the spotify example. Preferably one example instead of 2.

**Comment by phr0z** [comment]
@emontnemery 

Yes Im not sure I understand. To me it seems like the multizone example is for handling chromecast members dynamically, that's not what (at least Im) we're after here. 

The APP ID ("master device") I check for only launches if it the cast is initiated on a group. (which I think pychromecast already handle the members for?)

Go ahead and extend if I misunderstood.

Please excuse me. This is my first encounter with python.

**Comment by emontnemery** [comment]
> To me it seems like the multizone example is for handling chromecast members dynamically, that's not what (at least Im) we're after here.

What I tried to explain before is that there might be other users already casting. Hence, just looking for a cast which has the spotify app launched is not good enough, we need to make sure that cast is a member of the group we want to cast to.

I'll update the example to show how this can be done.

**Comment by emontnemery** [comment]
@fondberg, @phr0z Please have a look here: #294

**Comment by fondberg** [comment]
@emontnemery looks promising. I will test this as soon as I can

**Comment by phr0z** [comment]
@emontnemery 

Ah yes I see, nice!

Seems to be working properly.
