### ISSUE TITLE
'player_state': 'BUFFERING'

### ISSUE THREAD

**Issue by TorokLev** [balloob/pychromecast#298]
Hi,

For some reason I cannot make PyChromecast 3.2.2 to play an mp3 with Ubuntu 16.04 with Chromecast audio with firmware version 1.39.154182

Initially the Device / MC Status:

`
DeviceStatus(friendly_name='Family Room speaker', model_name='Chromecast Audio', manufacturer='Google Inc.', uuid=UUID('73005219-71ee-d27d-3002-575524bf9fea'), cast_type='audio')
CastStatus(is_active_input=None, is_stand_by=None, volume_level=0.32436779141426086, volume_muted=False, app_id=None, display_name=None, namespaces=[], session_id=None, transport_id=None, status_text='')
`

MediaController connects and looks like as it started to play but it remains in the following state:

`
<MediaStatus {'track': None, 'episode': None, 'player_state': 'BUFFERING', 'supports_skip_backward': False, 'content_type': 'audio/mp3', 'title': None, 'idle_reason': None, 'album_artist': None, 'last_updated': datetime.datetime(2019, 6, 23, 6, 31, 31, 758401), 'supports_stream_volume': True, 'supported_media_commands': 274447, 'current_subtitle_tracks': [], 'supports_skip_forward': False, 'series_title': None, 'content_id': 'http://localhost:9000/Jethro%20Tull/Living%20In%20The%20Past/11%20Inside.mp3', 'volume_muted': False, 'artist': None, 'supports_seek': True, 'volume_level': 1, 'stream_type': 'BUFFERED', 'supports_stream_mute': True, 'current_time': 0, 'media_custom_data': {}, 'images': [], 'season': None, 'metadata_type': None, 'supports_pause': True, 'playback_rate': 1, 'album_name': None, 'media_metadata': {}, 'duration': None, 'subtitle_tracks': {}, 'media_session_id': 1}>
`

Does anybody have an idea what is going wrong?

Thanks,
Lev

**Comment by karthikpanicker** [comment]
@TorokLev from the media status above, looks like you are trying to play media hosted at http://localhost:9000/Jethro%20Tull/Living%20In%20The%20Past/11%20Inside.mp3. I hope you have this in your Ubuntu's local webserver. Please note that chromecast will try to connect to this url, and localhost in Chromecast's context is itself. Can you try providing the ip address of your machine and ensure that your machines ip is reachable for chromecast.

**Comment by TorokLev** [comment]
Hi Karthik,
Yes, I am trying to play that track. The track is served by a python simplewebserver.
I can download the file from that webserver by a chrome browser using external interface.
I don't l know how can make sure that the chromecast can access this web server but I know that I can play stream by the cast functionality of a chrome browser on the same machine. So I assume it can download it.
Any more idea?
Thanks.

**Comment by ssieb** [comment]
You are sending a url that points to localhost. That works for Chrome because you are running that on the same computer. You need to replace localhost in the url with the IP address of your computer.

**Comment by TorokLev** [comment]
You are correct. Although I started a web server with external accessible external interface, I passed an URL with Localhost. Sorry.
