### ISSUE TITLE
Can this be used to cast local mp3's to chromecast audio?

### ISSUE THREAD

**Issue by thedaynos** [balloob/pychromecast#303]
Hi, just wondering about chromecast audio compatibility as well as casting a local mp3.  

I have audio file 2.mp3 in the same directory as my code and I tried:
cast = next(cc for cc in chromecasts if cc.device.friendly_name=="Living Room")
cast.wait()
mc = cast.media_controller
mc.play_media('2.mp3', 'audio/mp3')
print(mc.status)

I'm not getting any error message, but i can't hear anything happen either. It isn't giving me the noise it usually gives when I connect either.

If casting a local mp3 won't work then I can try plex.
Thanks!

**Comment by elibroftw** [comment]
Check out my project: https://github.com/elibroftw/music-caster.
I'm trying to enable chromecast support right now though. It works on Google Home Mini but not on my Chromecast.

**Comment by elibroftw** [comment]
Actually you'll have to wait some time, my code is device specific

**Comment by thedaynos** [comment]
Thank you!

**Comment by frakman1** [comment]
@elibroftw Nice project, but what's a quick way to cast an mp3 file in a line or two of python?

**Comment by elibroftw** [comment]
It can't be done in a line or two, but here's the minimum.
note that you need to define FILE_PATH and cast
```py
import flask
import socket
os.chdir(os.getcwd()[:3])  # set drive as the working dir
PORT = 2001
app = Flask(__name__, static_folder='/', static_url_path='/')
while True:
        try:
            threading.Thread(target=app.run, daemon=True, kwargs={'host': '0.0.0.0', 'port': PORT}).start()
            break
        except OSError: PORT += 1
s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
s.connect(('8.8.8.8', 80))
ipv4_address = s.getsockname()[0]
s.close()
drive = file_path[:3]
file_path_obj = Path(FILE_PATH)
if drive != os.getcwd().replace('\\', '/'):
    new_file_path = f'{cc_music_dir}/{file_path_obj.name}'
    copyfile(file_path, new_file_path)
else: new_file_path = file_path
uri_safe = Path(new_file_path).as_uri()[11:]
url = f'http://{ipv4_address}:{PORT}/{uri_safe}'
cast.wait()
mc = cast.media_controller
mc.play_media(url)  # NOTE: no thumbnail or metadata will show
```
