### ISSUE TITLE
Exploring existing namespaces instructions

### ISSUE THREAD

**Issue by rbclark** [balloob/pychromecast#304]
I am trying to investigate how to add a new app to pychromecast however I am having trouble with the "Exploring existing namespaces" instructions. It seems `chrome://net-internals/#capture` has been replaced with `chrome://net-export`. I've followed the instructions provided on the `chrome://net-internals/#capture` page and have managed to import a net-export however I have been unable to find the `Tr@n$p0rt` section. Are there any updated instructions available for someone new to this project like me who is trying to get started?

**Comment by Eerovil** [comment]
When using https://netlog-viewer.appspot.com/#events and going through all `SOCKET`s I was able to find one that has a lot of JSON data. I'm pretty sure it's correct since it has stuff like
```
t= 6843 [st= 6654]  SSL_SOCKET_BYTES_SENT
                    --> byte_count = 154
                    --> bytes =
                      00 00 00 96 08 00 12 13  73 65 6E 64 65 72 2D 7A      .. ..sender-z
                      37 69 39 64 65 62 34 66  77 6F 6F 1A 0A 72 65 63   7i9deb4fwoo..rec
                      65 69 76 65 72 2D 30 22  23 75 72 6E 3A 78 2D 63   eiver-0"#urn:x-c
                      61 73 74 3A 63 6F 6D 2E  67 6F 6F 67 6C 65 2E 63   ast:com.google.c
                      61 73 74 2E 72 65 63 65  69 76 65 72 28 00 32 4A   ast.receiver( 2J
                      7B 22 72 65 71 75 65 73  74 49 64 22 3A 31 35 30   {"requestId":150
                      39 35 32 30 32 39 2C 22  74 79 70 65 22 3A 22 47   952029,"type":"G
                      45 54 5F 41 50 50 5F 41  56 41 49 4C 41 42 49 4C   ET_APP_AVAILABIL
                      49 54 59 22 2C 22 61 70  70 49 64 22 3A 5B 22 41   ITY","appId":["A
                      39 42 43 43 42 37 43 22  5D 7D                     9BCCB7C"]}
```
