### ISSUE TITLE
Is it possible to support Dyon TV?

### ISSUE THREAD

**Issue by ArnoldSchiller** [balloob/pychromecast#306]
castube and mkchromecast use pychromecast "No devices found"
https://github.com/ArnoldSchiller/dyontvcast/blob/master/finddyon.py
find the device and
https://github.com/ArnoldSchiller/dyontvcast/blob/master/cast.sh
youtube Cast should be possible.

**Comment by balloob** [comment]
You're showing a discovery for DIAL. This is Chromecast and is different protocol. So no, cannot be supported.
