### ISSUE TITLE
Status returns 'None'

### ISSUE THREAD

**Issue by cougarek** [balloob/pychromecast#307]
Python 3.6.3, executing against different Chromecast devices. Status returns nothing, device returns valid information.
```
>>> print(pychromecast.Chromecast(ip).status)
None
>>> print(pychromecast.Chromecast(ip).device)
DeviceStatus(friendly_name='Xxx', model_name='Unknown model name', manufacturer='Unknown manufacturer', uuid=UUID('xxx'), cast_type='cast')
```

**Comment by balloob** [comment]
It takes some time before the status is available. That's why all examples have a sleep in it:

https://github.com/balloob/pychromecast/blob/063ad9169294315dd80fca91935e674732b5ee9f/examples/blocking.py#L28-L31
