### ISSUE TITLE
non blocking search, and event listeners

### ISSUE THREAD

**Issue by tbowmo** [balloob/pychromecast#310]
I have created a chromecast <-> mqtt integrator, where I now use nonblocking search for chromecasts. (https://github.com/tbowmo/chromecastcontrol)

If I just leave the search open forever, then after a while it will detect the same chromecasts again and again..

When I detect a new chromecast, I create a new event handler class, that passes the chromecast events on to mqtt. The problem is that if I just continue adding a new event listener to each and every chromecast that is detected, I end up with multiple event listeners for the same chromecast, which then all transmit status to mqtt, and creates a mess..

I have been looking at the code for pychromecast, and I can't find any place to unregister event handlers. Can we add this? 

Then I can unregister an eventhandler for a "defunct" chromecast, before it is added again.

**Comment by Hellowlol** [comment]
Why not register the chromecast you have already seen before you add the handler?

**Comment by tbowmo** [comment]
I'm not sure that I follow your suggestion.. 

I have something like the following (right now)
```
def main_loop():
    casters = {}
    def callback(chromecast):
        chromecast.connect()
        nonlocal casters
        name = chromecast.device.friendly_name
        print('Found :', name)
        casters.update({name: ChromeEvent(chromecast, mqtt, args.root)})

    stop_discovery = pychromecast.get_chromecasts(callback=callback, blocking=False)

    while True:
        if (args.MAX>0 and len(casters) == args.MAX):
            stop_discovery()
        sleep(1)

```

Right now I define a number of max casters, which makes it stop listening for new casters. The problem is (as I see it) now and then pychromecast looses connection to the chromecast, and then it appears as a new chromecast.

Maybe I have just stared myself blind on this problem.. And miss some important python skills, in order to handle it.. :)

**Comment by Hellowlol** [comment]
I think i would have used a global casters. So before you do any commands in your event handler, check if the connection is still there (socketclient) and just remove if from casters if it isn’t.

**Comment by tbowmo** [comment]
It seems that the later versions have become much more stable, and does a much better job at keeping the connection to the chromecasts alive. So I'll close this for now..
