### ISSUE TITLE
Supported media commands in media.

### ISSUE THREAD

**Issue by tbowmo** [balloob/pychromecast#322]
Where is the numbers for CMD_SUPPORTED_xxx come from in media.py? Is it reverse engineered, or do we have a definition list from google?

I ask because the tidal app doesn't seem to report supported features correct, I can use queue_next() command to skip to the next track, but still it reports both supports_queue_next and supports_skip_forward as unsupported.

I use the supports_xx_xx to indicate if a given button is supported in a UI that I'm making in react.

**Comment by karthikpanicker** [comment]
@tbowmo I think this was reversed from javascript sdk for cast. Your might have already seen the URL in the source code for the JS cast sdk. 
http://www.gstatic.com/cast/sdk/libs/caf_receiver/v3/cast_receiver_framework.js
This is the section of the code with those numbers corresponding to each command.
`"cast.framework.messages.Command", {
		PAUSE: 1,
		SEEK: 2,
		STREAM_VOLUME: 4,
		STREAM_MUTE: 8,
		ALL_BASIC_MEDIA: 12303,
		QUEUE_NEXT: 64,
		QUEUE_PREV: 128,
		QUEUE_SHUFFLE: 256,
		QUEUE_REPEAT_ALL: 1024,
		QUEUE_REPEAT_ONE: 2048,
		QUEUE_REPEAT: 3072,
		SKIP_AD: 512,
		EDIT_TRACKS: 4096,
		PLAYBACK_RATE: 8192,
		LIKE: 16384,
		DISLIKE: 32768,
		FOLLOW: 65536,
		UNFOLLOW: 131072,
		STREAM_TRANSFER: 262144
	}, void 0);`

**Comment by tbowmo** [comment]
right, saw it just as I had written my question :)
I have to get my glasses, and dig through things to figure out why I do not get the correct indicators.
