### ISSUE TITLE
Is it possible to surf to a given URL (not audio/video)

### ISSUE THREAD

**Issue by Acer54** [balloob/pychromecast#329]
Hello, 
I am searching for a way to navigate with a Google-Nest-Hub to a given URL including a specific port (which is not youtube or tunein...)
The idea is to let the nest-hub open up a Chrome Window (which is available at the nest-hub) opening the URL of my home-automation (iobroker:8000) that I am able to "click" something (no keyboard-entry needed)

Is there any possibility with pychromecast?

**Comment by robertmuth** [comment]
yes it is possible but it does not seem to work with arbitrary urls (you have to try).
Example code is here:

https://github.com/robertmuth/mqtt2cast

**Comment by Acer54** [comment]
Hi Robert, thanks for this hint! Did not know about DashCast.
Based on your code, I've made it "display" with this code:
`>>> import pychromecast
>>> import pychromecast.controllers.dashcast as dashcast
>>> cast = pychromecast.Chromecast(host="192.168.178.30")
>>> cast.wait()
>>> cast.dashcast = dashcast.DashCastController()
>>> dc = cast.dashcast
>>> cast.register_handler(dc)
>>> dc.load_url("http://external_url:8082/linking/back.html#tolocalhost")`

The unexpected downside is, that it is only "displaying" the page and do not accept any interaction (clicking on lamps or other things which I can control from this page...)
Do you know a solution for this behavior ?

**Comment by Acer54** [comment]
Ah, found it by my own^^. You just have to use the "force=True" switch when loading the Url:
`dc.load_url("http://external_url:8082/linking/back.html#tolocalhost", force=True)`

Now its working like I wanted it to ;-) 
Thank you VERY MUCH Robert, you made my day!

Now I will get this in a short script and trigger it via IFTT with a voice command and I can make my home-automation system controllable with my Google Hub :-)
