### ISSUE TITLE
Casting stuck on blue Chromecast logo with local files

### ISSUE THREAD

**Issue by JonasVautherin** [balloob/pychromecast#344]
I can connect to my Chromecast device and start sending a movie. I can Chromecast remote movies (following the example, big buck bunny works, for instance). But whenever I try to broadcast a video that I have locally on my computer, it gets stuck on the blue Chromecast logo, without showing an error.

What could be happening, and how can I debug more to understand what is happening?

**Comment by balloob** [comment]
All urls send to Chromecast should be accessible by the Chromecast. Any local file on the computer running PyChromecast is not accessible.

**Comment by JonasVautherin** [comment]
Oh, I guess that's why mkchromecast creates a flask server, then. So probably I have an issue with mkchromecast, I guess. Thanks!
