### ISSUE TITLE
unable to get the example.py script to work

### ISSUE THREAD

**Issue by DanOBrien** [balloob/pychromecast#38]
When I run the example script, I get the following:

~/pychromecast-master$ python example.py
Traceback (most recent call last):
  File "example.py", line 16, in <module>
    cast = pychromecast.get_chromecast()
  File "/home/dobrien/pychromecast-master/pychromecast/__init__.py", line 121, in get_chromecast
    for ip in discover_chromecasts(1)]
  File "/home/dobrien/pychromecast-master/pychromecast/__init__.py", line 151, in __init__
    self.host = socket.gethostbyname(host)
TypeError: must be string, not tuple
Exception AttributeError: "'Chromecast' object has no attribute 'socket_client'" in  ignored

I'm using Python 2.7.3
~/pychromecast-master$ python --version
Python 2.7.3

**Comment by balloob** [comment]
That's interesting, that means that zeroconf returned a tuple instead of a string. 

Locally on your machine, could you change `/home/dobrien/pychromecast-master/pychromecast/init.py` and add a new line before line 151 that says `print(host)` and tell me the output ?

**Comment by CWempe** [comment]
I have the same issue.
So I added the print(host) you asked for.

root@htpc:/tmp/pychromecast-master# python ./example.py
(u'Wohnzimmer.local.', 8009)
Traceback (most recent call last):
  File "./example.py", line 16, in <module>
    cast = pychromecast.get_chromecast()
  File "/tmp/pychromecast-master/pychromecast/__init__.py", line 121, in get_chromecast
    for ip in discover_chromecasts(1)]
  File "/tmp/pychromecast-master/pychromecast/__init__.py", line 152, in __init__
    self.host = socket.gethostbyname(host)
TypeError: must be string, not tuple
Exception AttributeError: "'Chromecast' object has no attribute 'socket_client'" in  ignored

"Wohnzimmer" means "living room" in german and is the name of my chromecast.

**Comment by balloob** [comment]
For now, if you want to play with it, add a line before [line 151](https://github.com/balloob/pychromecast/blob/master/pychromecast/__init__.py#L151) that says `host = host[0]`. I'll push a proper fix when I get back home tonight.

**Comment by CWempe** [comment]
Thanks.

Now I get this:
-------------
root@htpc:/tmp/pychromecast-master# python ./example.py

DeviceStatus(friendly_name='Wohnzimmer', model_name='Eureka Dongle', manufacturer='Google Inc.', api_version=(1, 0))

CastStatus(is_active_input=False, is_stand_by=True, volume_level=1.0, volume_muted=False, app_id=u'E8C28D3C', display_name=u'Backdrop', namespaces=[u'urn:x-cast:com.google.cast.sse'], session_id=u'ED627B11-7A05-4A6E-0B1D-BE6DBEAC297C', transport_id=u'web-0', status_text='')

None

Playing media
No handlers could be found for logger "pychromecast.socket_client"
Traceback (most recent call last):
  File "./example.py", line 40, in <module>
    "sample/BigBuckBunny.mp4"), "video/mp4")
  File "/tmp/pychromecast-master/pychromecast/controllers/media.py", line 185, in play_media
    self.send_message(msg, inc_session_id=True)
  File "/tmp/pychromecast-master/pychromecast/controllers/__init__.py", line 77, in send_message
    "application.").format(self.namespace))
pychromecast.error.UnsupportedNamespace: Namespace urn:x-cast:com.google.cast.media is not supported by runningapplication.
-------------

Do you want me to create a separate issue for this?
You may want to add some checks to prevent this error messages. :)

But no hurry.
I am not at home either. ;)

**Comment by DanOBrien** [comment]
Here's what I've added to the __init__.py

        # Resolve host to IP address (line 150)
        print(host)
        host = host[0]
        print(host)
        self.host = socket.gethostbyname(host)

And here's the output:
~/pychromecast-master$ python example.py
(u'Living room.local.', 8009)
Living room.local.
Traceback (most recent call last):
  File "example.py", line 16, in <module>
    cast = pychromecast.get_chromecast()
  File "/home/dobrien/pychromecast-master/pychromecast/__init__.py", line 121, in get_chromecast
    for ip in discover_chromecasts(1)]
  File "/home/dobrien/pychromecast-master/pychromecast/__init__.py", line 154, in __init__
    self.host = socket.gethostbyname(host)
socket.gaierror: [Errno -2] Name or service not known
Exception AttributeError: "'Chromecast' object has no attribute 'socket_client'" in  ignored

**Comment by balloob** [comment]
Which platform are you running this on?

**Comment by DanOBrien** [comment]
I'm on  Ubuntu 12.04.5 LTS (GNU/Linux 3.2.0-74-generic i686)

**Comment by CWempe** [comment]
Me too.

Ubuntu 12.04.5 LTS
3.2.0-74-generic
Python 2.7.3

**Comment by balloob** [comment]
It seems that zeroconf is enabled by default [since Ubuntu version 9.04](https://help.ubuntu.com/community/HowToZeroconf) but just as a sanity check, do you guys have zeroconf disabled maybe?

**Comment by CWempe** [comment]
I am not sure how to check this.

But I am using an htpc (yaVDR with XBMC) and my nfs-shares are mounted via avahi.
I think it is like zeroconfig or uses it.

**Comment by balloob** [comment]
Avahi is the same, so that shouldn't be an issue then.

I have just pushed 2bee5464eef8a9cd700e93c86645c308f2799f5d that should fix the discovery and make the example script work again, sorry about that.

I'll open a different issue for being unable to resolve the Chromecast hostname
