### ISSUE TITLE
Unable to resolve local hostname to IP

### ISSUE THREAD

**Issue by balloob** [balloob/pychromecast#39]
Python is not able on all platforms to resolve a local hostname to an IP address.

@DanOBrien wrote about this in #38:

Here's what I've added to the __init__.py

        # Resolve host to IP address (line 150)
        print(host)
        host = host[0]
        print(host)
        self.host = socket.gethostbyname(host)

And here's the output:
```
~/pychromecast-master$ python example.py
(u'Living room.local.', 8009)
Living room.local.
Traceback (most recent call last):
  File "example.py", line 16, in <module>
    cast = pychromecast.get_chromecast()
  File "/home/dobrien/pychromecast-master/pychromecast/__init__.py", line 121, in get_chromecast
    for ip in discover_chromecasts(1)]
  File "/home/dobrien/pychromecast-master/pychromecast/__init__.py", line 154, in __init__
    self.host = socket.gethostbyname(host)
socket.gaierror: [Errno -2] Name or service not known
Exception AttributeError: "'Chromecast' object has no attribute 'socket_client'" in  ignored
```

**Comment by balloob** [comment]
I have just pushed d32ec088c6ab7a21015a51c2b66cb30e17399647 which tries to resolve this issue. Can you test if this resolves your problem @DanOBrien ?

**Comment by CWempe** [comment]
Just my 2 cents:
I think "Living room.local." cannot be a valid hostname/FQDN, because there is a blank space.
Maybe the hostname is different from chromecast-name.

Remember my chromecast is labled "Wohnzimmer".
But my dns server (home router "fritz.box") has another hostname for it. "chromecast.fritz.box."
> root@htpc:/tmp/pychromecast-master# nslookup chromecast
> Server:         192.168.1.1
> Address:        192.168.1.1#53
> 
> Name:   chromecast.fritz.box
> Address: 192.168.1.13
> 
> root@htpc:/tmp/pychromecast-master# nslookup 192.168.1.13
> Server:         192.168.1.1
> Address:        192.168.1.1#53
> 
> 13.1.168.192.in-addr.arpa       name = Chromecast.fritz.box.
> 
> root@htpc:/tmp/pychromecast-master# nslookup wohnzimmer.local.
> Server:         192.168.1.1
> Address:        192.168.1.1#53
> 
> ** server can't find wohnzimmer.local.: NXDOMAIN

However, it seems to work for me and I don't know if this is any help to you. :)

**Comment by balloob** [comment]
I know a space seems weird but it works on my Mac, but then again, that gives no guarantee that it is part of a standard ;-)

```
$  ping "Living Room.local."
PING living\032room.local (192.168.1.9): 56 data bytes
64 bytes from 192.168.1.9: icmp_seq=0 ttl=64 time=10.862 ms
64 bytes from 192.168.1.9: icmp_seq=1 ttl=64 time=11.671 ms
64 bytes from 192.168.1.9: icmp_seq=2 ttl=64 time=4.614 ms
64 bytes from 192.168.1.9: icmp_seq=3 ttl=64 time=2.139 ms
64 bytes from 192.168.1.9: icmp_seq=4 ttl=64 time=4.675 ms
64 bytes from 192.168.1.9: icmp_seq=5 ttl=64 time=8.026 ms
^C
--- living\032room.local ping statistics ---
6 packets transmitted, 6 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 2.139/6.998/11.671/3.476 ms
```

**Comment by CWempe** [comment]
According to wikipedia (https://en.wikipedia.org/wiki/Hostname) "No [..] or white space are permitted.".

I don't know...

**Comment by DanOBrien** [comment]
My Verizon FiOS "ActionTec" router shows the device listed as "Chromecast" in the DHCP connection list/DNS server. When setting up my Chromecast, I picked the name "Living Room", as it's "Friendly name" so I'm sure the space comes from the device upon discovery.

**Comment by DanOBrien** [comment]
Someone turned the TV on at home so now I can finally test.  The latest update appears to be working. 

~/pychromecast-master$ python example.py
10.10.1.51

DeviceStatus(friendly_name='Living room', model_name='Eureka Dongle', manufacturer='Google Inc.', api_version=(1, 0))

etc.....
etc.....

I'll see what happens on screen when I get home, so far it looks good.
