### ISSUE TITLE
Sleep required between calls

### ISSUE THREAD

**Issue by geuben** [balloob/pychromecast#40]
This works:
```python
import pychromecast
import time
cast = pychromecast.get_chromecast()
print cast.device
time.sleep(1)
print cast.status
```

This doesn't, show status of None:
```python
import pychromecast
import time
cast = pychromecast.get_chromecast()
print cast.device
print cast.status
```

**Comment by balloob** [comment]
That's exactly how it is done in [example.py](https://github.com/balloob/pychromecast/blob/master/example.py#L22) :+1:

**Comment by geuben** [comment]
Which is how I figured out how to get it to work. Doesn't make it right though.

Do you know why the sleep is required? Would be nice to at least document its requirement.

**Comment by balloob** [comment]
PyChromecast communicates with Chromecasts using a socket. When you initialize an object it will start the connection. It takes a bit of time for the Chromecast to report its initial status back to PyChromecast.

**Comment by geuben** [comment]
I think it would be better for the library to block until the connection is established and the status is available. You could make an optional non_blocking call too incase there are people that wan't to use it in that way.
