### ISSUE TITLE
Stream Website or Picture

### ISSUE THREAD

**Issue by 1337sup3rh4x0r** [balloob/pychromecast#58]
Hello,
is it also possible to stream a website (html document or link) or a picture (jpeg, png, whatever) to chromecast with this tool?

I would like to create an info screen that is displayed at certain times and triggered from a server.

Is this possible with your tool?

**Comment by balloob** [comment]
You can play any media file, picture or video. Website is not supported
directly but if you make a Chromecast app (which is a website), you can
cast it with this tool.

**Comment by 1337sup3rh4x0r** [comment]
Thanks, this sounds good!
Can that chromecast app also be run headless on a server or do I need to cast that manually via chrome and the cast extension?
Otherwise, patching together an image and casting that via your tool seems more straightforward...

**Comment by balloob** [comment]
Chromecasts apps are hosted in the cloud and are just HTML etc. PyChromecast can be used to cast that app to your TV.

**Comment by 1337sup3rh4x0r** [comment]
Ah I understand. So basically I cannot cast a "private" html page? This all goes through google's servers? Is this also true for casting pictures from a local source?

**Comment by balloob** [comment]
No, pictures or movies can be triggered right away

**Comment by 1337sup3rh4x0r** [comment]
Thank you, then I will go ahead and stitch my Infoscreen together from images and stream that.
Thanks for your support!

**Comment by unknownguy2002** [comment]
I am interested, how did you do that, may I ask?

**Comment by 1337sup3rh4x0r** [comment]
It's been a more complicated project.
It mainly consists of a headless virtual machine in which screenshots from several webpages are taken on a regular basis. This is done via "ghost" which is a python module. On a headless machine you need Xvcb running to be able to run a browser and take screenshots.
These screenshots are then cropped and stitched together, also with a python module "PIP".
The stitched image is saved into the root directory of a local webserver. 

The url of this image can then be sent to chromecast using pychromecast.

All the scripts need to be called e.g. every minute via a cronjob to get regular updates on the screen.

In my latest implementation I have skipped the stiching and built the infoscreen layout with the FTUI of the open source home automation FHEM. I therefore now only take one screenshot of this layout and copy it to the webserver to stream it to chromecast.

There are of course many ways to build the image, but to automate the streaming, I haven't found a better way than via ghost and Xvcb.

**Comment by unknownguy2002** [comment]
Impressive! 👍

**Comment by fivestones** [comment]
For people coming here looking for an easier way to do this like I was: catt (cast all the things) at https://github.com/skorokithakis/catt can send websites (including a dashboard) to a chromecast from the commandline, no need to make a virtual machine and take screenshots and all that. Just cast the website itself.

**Comment by madarp** [comment]
Been looking for exactly this `catt` , thanks for leaving that breadcrumb!
