### ISSUE TITLE
Send local video to chromecast

### ISSUE THREAD

**Issue by jaapz** [balloob/pychromecast#6]
Is there anyway using pychromecast to stream a file on the local filesystem to the chromecast using pychromecast? If not, which protocol needs to be implemented to do that? Because the chromecast is capable of doing this.

This would enable my `cast` command line tool to do:

    cast send file:///home/user/videos/holyvideosbatman.mp4

Which would be awesome!

**Comment by balloob** [comment]
Marked it as a wontfix.

The goal for PyChromecast is to offer a library that implements the Google Cast protocol. Serving video is therefore out of the scope of this project.

**Comment by abhayszambare** [comment]
here nice information is given on [How to chromecast from laptop (Mac and Windows)](https://everything4comp.blogspot.com/2017/12/chromecast-from-laptop-mac-and-windows.html)
