### ISSUE TITLE
remotedebug?

### ISSUE THREAD

**Issue by nlittlepoole** [balloob/pychromecast#61]
According to [this article](http://www.clift.org/fred/chromecast-displaying-arbitrary-urls-using-pychromecast.html) there should be a remotedebug.py that gives access to ```.crd_open_url()``` What happened to that? Is there anyway to mimic this functionality?

**Comment by minektur** [comment]
Read 2 or 3 blog entries later and see that google updated the firmware to disable that very useful feature.

Sigh
