### ISSUE TITLE
Trying to add title errors out with a KeyError

### ISSUE THREAD

**Issue by acoushawk** [balloob/pychromecast#70]
In the play_media function I'm getting an error when trying to pass a title value. It appears to be how it adds the new title to the 'msg' dictionary. I'm not sure what the API is looking for in terms of structure but this is what I believe it should be.

msg['customData']['payload'] = {'title':title}

That may or may not be correct but it's just my 2 cents.

Nice work though, helped me a ton!

**Comment by dylwhich** [comment]
I ran into this as well; you should just be able to do a pull as it's fixed in 9d7c206 (see #68)

**Comment by balloob** [comment]
Yep, this bug will go out in the next release.
