### ISSUE TITLE
get_chromecast is rather slow.

### ISSUE THREAD

**Issue by skorokithakis** [balloob/pychromecast#72]
The `get_chromecast` method is pretty slow when it performs the initial discovery. I have a stateless script that runs anew every time it is called, but is there something I can serialize and deserialize to make the discovery process quicker? I'll only ever use one Chromecast at a time, so it would be nice if I could save its address and other info to a file and just load that rather than do the complete discovery again.

How can that be done? Can it be added to the docs?

**Comment by rmkraus** [comment]
It is a bit slow, and sometimes unreliable. This is generally the case with network discovery, unfortunately.

You can load a specific Chromecast by IP Address like this:
```python
cast = pychromecast.Chromecast('192.168.10.5')
```
This will skip all discovery.

**Comment by skorokithakis** [comment]
That's exactly what I wanted, thank you!
