### ISSUE TITLE
Feature request: Kodi (XBMC) service addon?

### ISSUE THREAD

**Issue by Hedda** [balloob/pychromecast#79]
Would anyone be interested in making a Chromecast Audio (Cast) casting script for Kodi (formerly XBMC) in the form of an service addon for Kodi?

Kodi is an open source media player software has an integrated Python interpreter for running native addons inside Kodi, so it would be very cool if someone would make a Chromecast Audio addon for it based on pychromecast.

The foremost feature that I would like to have it so be able to playback music inside Kodi and have that output (cast) to Chromecast Audio, having Kodi act as a casting sender, however it would also be cool to have Kodi act as a Chromecast Audio receiver as well since you most likly have Kodi connected to your television with speakers anyway. 

For my own I think that Kodi (cast) output support would be awesome for multi-room music playback.

PS: To have Kodi act as a Chromecast Audio or Video reciever you could probably take ideas of the existing AirPlay / AirTunes service addon for Kodi.

**Comment by balloob** [comment]
This issue is out of scope for the pychromecast project.
