### ISSUE TITLE
'Chromecast' object has no attribute 'socket_client'

### ISSUE THREAD

**Issue by cburmeister** [balloob/pychromecast#83]
When trying to access a Chromecast that isn't plugged in via
`pychromecast.Chromecast(ip)` i'm getting an `AttributeError`:
```
Exception AttributeError: "'Chromecast' object has no attribute 'socket_client'" in <bound method Chromecast.__del__ of Chromecast('10.0.0.5', port=8009, device=None)> ignored
```

**Comment by tkalus** [comment]
@cburmeister, I think you want to use the `get_chromecast()` function and let it pass you a `Chromecast` object.

E.G.
```
...
>>> import pychromecast
>>> cast = pychromecast.get_chromecast(ip)
>>> cast
Chromecast('[ip]', port=[port], device=DeviceStatus(...), cast_type='cast'))
>>>
...
```

**Comment by techbliss** [comment]
yes i am getting the same on the other issue https://github.com/balloob/pychromecast/issues/81

**Comment by cburmeister** [comment]
Fixed by calling `Chromecast.disconnect()`:

https://github.com/balloob/pychromecast/blob/master/pychromecast/__init__.py#L381
