### ISSUE TITLE
netifaces breaks with Python 3.

### ISSUE THREAD

**Issue by skorokithakis** [balloob/pychromecast#85]
netifaces, which pychromecast depends on, won't install on Python 3 in some cases, breaking pychromecast and packages which depend on it. I've sent them a [pull request](https://bitbucket.org/al45tair/netifaces/pull-requests/7/fix-setup-in-case-theres-no-print/diff) but the project seems to be abandoned. Is there any way pychromecast could possibly move off netifaces?

**Comment by balloob** [comment]
It's part of zeroconf which we need for discovery

**Comment by skorokithakis** [comment]
Can you bundle your own version of netifaces? That way the offending `print` can be taken out, at least, enabling installation under Python 3.

**Comment by balloob** [comment]
No, PyPi is responsible for installing dependencies and we only depend on zeroconf.

**Comment by balloob** [comment]
Did you try emailing the author of netifaces ?

**Comment by skorokithakis** [comment]
Yes I did, and I received no response. I even issued a pull request. Currently this project is not installable on python 3.

**Comment by balloob** [comment]
Our tests run just fine and they get netifaces installed. When does the
error occurr?

**Comment by skorokithakis** [comment]
You can see the breakage here:

https://travis-ci.org/skorokithakis/catt/jobs/134025873

and the fix here:

https://bitbucket.org/al45tair/netifaces/pull-requests/7/fix-setup-in-case-theres-no-print/diff

**Comment by balloob** [comment]
Home Assistant has no problems installing pychromecast. We use tox which
calls "pip install -r". I think that you should be able to add that to
Travis to work around the issue. There is nothing that I can do here.
