### ISSUE TITLE
notify when change

### ISSUE THREAD

**Issue by minscof** [balloob/pychromecast#89]
I would like to be notified when there is a change in a cast device. Is it already available or on the roadmap ?

I try to do it by comparing cast object. It will be easier with a compare method like this one :
`
    def __eq__(self, other):
        if isinstance(other, self.__class__):
            return self.__dict__ == other.__dict__
        else:
            return False

    def __ne__(self, other):
        return not self.__eq__(other)
`

Could you add it ?

Thx

**Comment by balloob** [comment]
We already support status change listeners

**Comment by minscof** [comment]
Good, is there any sample to show how it works ?
