### ISSUE TITLE
How to cast a chrome tab?

### ISSUE THREAD

**Issue by Tontiwisk** [balloob/pychromecast#91]
I currently want to cast a static webpage (signage stuff) 24/7.
But sometimes the network drops and I want to automate the re-cast process.
It doesn't seem that this library can interface with the chrome browser or the chromecast extension at all.

I know I could make a custom receiver, but I'd like to keep the chromecast working locally in case my WAN drops.

Any ideas on how to do this?

**Comment by balloob** [comment]
Thats not possible. A custom receiver is  the way to go
