### ISSUE TITLE
Doesn't detect despite being able to cast

### ISSUE THREAD

**Issue by Pizzaface** [balloob/pychromecast#98]
I have my ChromeCast set up (actually have 2 of them, one in another room), and pychromecast doesn't detect either, despite both not being used (which I don't know if this would be an issue anyway), and being able to cast through the app. 

I've verified that the computer and chromecast are connected to the same network (Repeater through my home), and have even reset my WiFi multiple times. It's Spotty, but it detects occasionally.

No complex code, just running a simple:

`print list(pychromecast.get_chromecasts_as_dict().keys())`

Shows nothing but:
`[]`

ChromeCast Gen1 

Thanks in advance!

EDIT: I should note I'm using Python 2.7

**Comment by FicusFroman** [comment]
did you fix your problem?  I'm new to python, but facing similar problem, I get dict.keys([]) from that code.  But I can connect to the cast and successfully cast when selecting the device from its ip address.
