### ISSUE TITLE
Cannot install on synology NAS

### ISSUE THREAD

**Issue by brownad** [balloob/pychromecast#99]
Hi,

I have tried to install this dependency on Synology via home assistant installation but fails as it needs to compile is there a way to deploy this?

**Comment by KalleSven** [comment]
brownad, I've struggled with the same issue a while back, but finally got it working a while ago. The main issue for me was to compile netifaces for DS413+ (powerPC CPU). If remember correctly, I ended up cross compiling a Python Wheel on Ubuntu and then installing the wheel on my Synology NAS. I started out on this page: https://github.com/SynoCommunity/spksrc/wiki/Using-wheels-to-distribute-Python-solutions

Unfortunately, I am very new to this, so I am not sure I can help out any further. 

Good luck!
